# yaml-language-server: $schema=https://raw.githubusercontent.com/cuioss/cuioss-organization/main/.github/actions/read-project-config/schema.json
name: cui-jsf-test-basic

release:
  current-version: 4.1.2
  next-version: 4.0-SNAPSHOT
  create-github-release: true

sonar:
  project-key: cuioss_cui-jsf-test-basic

pages:
  reference: cui-jsf-test-basic

github-automation:
  auto-merge-build-versions: true
  auto-merge-build-timeout: 300

consumers:
  - cuioss-parent-pom:version.cui.test.jsf.basic

dependency-propagation:
  group-id: de.cuioss.test
  artifact-id: cui-jsf-test-basic
  scope: dependency
