= cui-jsf-test-basic

== Status

image:https://github.com/cuioss/cui-jsf-test-basic/actions/workflows/maven.yml/badge.svg[Java CI with Maven,link=https://github.com/cuioss/cui-jsf-test-basic/actions/workflows/maven.yml]
image:http://img.shields.io/:license-apache-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0.html]
image:https://maven-badges.herokuapp.com/maven-central/de.cuioss.test/cui-jsf-test-basic/badge.svg[Maven Central,link=https://maven-badges.herokuapp.com/maven-central/de.cuioss.test/cui-jsf-test-basic]

https://sonarcloud.io/summary/new_code?id=cuioss_cui-jsf-test-basic[image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-jsf-test-basic&metric=alert_status[Quality
Gate Status]]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-jsf-test-basic&metric=ncloc[Lines of Code,link=https://sonarcloud.io/summary/new_code?id=cuioss_cui-jsf-test-basic]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-jsf-test-basic&metric=coverage[Coverage,link=https://sonarcloud.io/summary/new_code?id=cuioss_cui-jsf-test-basic]

https://cuioss.github.io/cui-jsf-test-basic/about.html[Generated Documentation on github-pages]

== What is it?

Extension for http://myfaces.apache.org/test/index.html[MyFaces-Test] that uses the mock-based infrastructure and adds certain aspects in order to simplify its usage in the portal-context:

* Convenient programmatic configuration of JSF-context
* Specific base-classes for conveniently testing aspects like
** `AbstractBeanTest`
** `AbstractValidatorTest`
** `AbstractConverterTest`
** `AbstractComponentTest`
** `AbstractUiComponentTest`
** `AbstractComponentRendererTest`
* Tooling for generating (partial-)HTML-trees including the corresponding Assertions
* Additional Mocks completing the ones provided from myfaces-test
* Integration into https://github.com/cuioss/cui-test-value-objects[cui-test-value-objects] framework
* Baseline is JSF 4.1

== Versions

- JSF 4+: main-branch -> Release-Versions 4.x
- JSF 2.3: https://github.com/cuioss/cui-jsf-test-basic/releases/tag/2.0.2[Release 2.0.2] https://github.com/cuioss/cui-jsf-test-basic/tree/release/v2[2er-Release-Branch]

=== Maven Coordinates

[source,xml]
----
    <dependency>
        <groupId>de.cuioss.test</groupId>
        <artifactId>cui-jsf-test-basic</artifactId>
        <version>4.1.0</version>
        <scope>test</scope>
    </dependency>
----

== Documentation

link:doc/usage.adoc[Usage Documentation]
