== About

Extension for http://myfaces.apache.org/test/index.html[MyFaces-Test] that uses the mock-based infrastructure and adds certain aspects in order to simplify its usage in the portal-context:

* Convenient programmatic configuration of JSF-context
* Specific base-classes for conveniently testing specific aspects like AbstractBeanTest, AbstractValidatorTest, AbstractConverterTest, AbstractComponentTest, AbstractUiComponentTest, AbstractComponentRendererTest
* Lots of tooling for generating (partial-) HTML-trees including the corresponding Assertions
* Additional Mocks completing the ones provided from myfaces-test
* Integration into ValueObject framework
* Baseline is JSF 2.3

== How To use it

=== Simple Usage

If you want to add a complete JSF-runtime-setup to a certain test just add the annotation

[source,java]
----
@EnableJsfEnvironment
class FacesTestEnabledTest {
----

The corresponding extension takes care for handling the JSF-Setup including resetting it for each test.

=== Add Configuration

As a next step you maybe want to add additional configuration. This can be done either by type

[source,java]
----
@EnableJsfEnvironment
@JsfTestConfiguration(BasicApplicationConfiguration.class)
class FacesTestEnabledTest {
----

Or via callback interface

[source,java]
----
@EnableJsfEnvironment
class AccordionRendererTest
        extends AbstractComponentRendererTest<AccordionRenderer> implements ComponentConfigurator {

    @Override
    public void configureComponents(final ComponentConfigDecorator decorator) {
        decorator.registerRenderer(BootstrapPanelRenderer.class);
    }
----

The framework takes care of calling the callback methods at the correct time prior to each test

Available Extension-Types:

* de.cuioss.test.jsf.config.ApplicationConfigurator
* de.cuioss.test.jsf.config.BeanConfigurator
* de.cuioss.test.jsf.config.ComponentConfigurator
* de.cuioss.test.jsf.config.RequestConfigurator

Corresponding Configurator-Types:

* de.cuioss.test.jsf.config.decorator.ApplicationConfigDecorator
* de.cuioss.test.jsf.config.decorator.BeanConfigDecorator
* de.cuioss.test.jsf.config.decorator.ComponentConfigDecorator
* de.cuioss.test.jsf.config.decorator.RequestConfigDecorator

See the javadoc-documentation for the actual usage


=== Fine grained control

For cases you want to modify the tests more fine grained or want to have access on FacesContext, ExternalContext and Co. you can use de.cuioss.test.jsf.util.JsfEnvironmentConsumer

[source,java]
----
@EnableJsfEnvironment
class FacesTestEnabledTest implements JsfEnvironmentConsumer {

    @Setter
    @Getter
    private JsfEnvironmentHolder environmentHolder;

    @Test
    void shouldProvideJsfObjects() {
        assertNotNull(environmenHolder);
        assertNotNull(getApplication());
        assertNotNull(getApplicationConfigDecorator());
        assertNotNull(getBeanConfigDecorator());
        assertNotNull(getComponentConfigDecorator());
        assertNotNull(getExternalContext());
        assertNotNull(getFacesContext());
        assertNotNull(getRequestConfigDecorator());
        assertNotNull(getResponse());
    }
----

JsfEnvironmentHolder provides programmatic access to FacesContext, ExternalContext and Co. as well as the variants for programmatically configuring the environment.
In addition, it provides two navigation related assertions:

[source,java]
----
@EnableJsfEnvironment
class FacesTestEnabledTest implements JsfEnvironmentConsumer {
  @Setter
  @Getter
  private JsfEnvironmentHolder environmentHolder;

   @Test
   void shouldAssertNavigationOutcome() {
       getApplicationConfigDecorator().registerNavigationCase(OUTCOME, TO_VIEW_JSF);
       getApplication().getNavigationHandler().handleNavigation(getFacesContext(), null, OUTCOME);
       assertNavigatedWithOutcome(OUTCOME);
   }

   @Test
   void shouldAssertRedirect() throws IOException {
       getExternalContext().redirect(TO_VIEW_JSF);
       assertRedirect(TO_VIEW_JSF);
   }
----


## Testing a Validator
Testing a validator is straight-forward. You focus on the actual data to be checked, by using the fluent-api on TestItems. The api-tests are implicitly run. Additional configuration can be done using the mechanisms described previously.
The callback method for configuring the validator is optional.

[source,java]
----

class AbstractValidatorTestTest extends AbstractValidatorTest<LengthValidator, String> {

   @Override
   public void populate(final TestItems<String> testItems) {
       testItems.addValid("1").addValid("abc").addInvalidWithMessage("123456",
               LengthValidator.MAXIMUM_MESSAGE_ID);
   }

   @Override
   public void configure(final LengthValidator validator) {
       validator.setMaximum(5);
   }
----

Take a closer look at the parameter addInvalidWithMessage. It passes and checks the key not a resolved message, see de.cuioss.test.jsf.junit5.EnableJsfEnvironment#useIdentityResouceBundle for an explanation of the resource-bundle handling.

## Testing a Converter
Testing a converter is straight-forward. You focus on the actual data to be checked, by using the fluent-api on TestItems. The api-tests are implicitly run. Additional configuration can be done using the mechanisms described previously.
The callback method for configuring the converter is again optional.

[source,java]
----

class AbstractConverterTestTest extends AbstractConverterTest&lt;IntegerConverter, Integer&gt; {

   @Override
   public void populate(final TestItems<Integer> testItems) {
       testItems.addRoundtripValues("1", "122", "2132121").addInvalidString("a")
               .addInvalidStringWithMessage("a", "javax.faces.converter.IntegerConverter.INTEGER")
               .addInvalidObject(Boolean.TRUE)
               .addInvalidObjectWithMessage(Boolean.FALSE, "javax.faces.converter.STRING")
               .addValidString("13").addValidStringWithObjectResult("17", 17)
               .addValidObject(2)
               .addValidObjectWithStringResult(14, "14");
   }

   @Override
   public void configure(IntegerConverter toBeConfigured) {
       // Optional configuration for converter-test
   }

}

----

## Testing a Managed / Named Bean
Testing the attributes and canonical Object-Methods of a given Managed / Named Bean

[source,java]
----

@PropertyReflectionConfig(
 defaultValued = { MediumComplexityBean.STRING_WITH_DEFAULT_VALUE })
@ObjectTestConfig(
 equalsAndHashCodeExclude = MediumComplexityBean.ATTRIBUTE_NO_OBJECT_IDENTITY_STRING)
class AbstractBeanTestTest extends AbstractBeanTest<MediumComplexityBean> {

}

----

## Testing a Component
Testing a component-class usually consists of testing the api-contract, the attribute handling (incl. Value-Expressions), and custom tests. Api and attributes are tested declarative.

[source,java]
----

@VerifyComponentProperties(of = { "offTextValue", "offTextKey" ,"onTextValue", "onTextKey","titleValue", "titleKey","rendered", "disabled" })
@JsfTestConfiguration(CoreJsfTestConfiguration.class)
class SwitchComponentTest extends AbstractComponentTest<SwitchComponent> {

   @Test // Tests actual logic
   void shouldResolvePassThroughAttributes() {
       SwitchComponent underTest = anyComponent();
       underTest.setDisabled(false);
       assertEquals(ImmutableMap.of("data-switch-disabled", "false"),
                underTest.resolvePassThroughAttributes());
       underTest.setDisabled(true);
       assertEquals(ImmutableMap.of("data-switch-disabled", "true"),
                underTest.resolvePassThroughAttributes());
   }
}

----
## Testing a Component with Renderer
This is a complex real-world-example bringing together many aspects of the test-framework

[source,java]
----

@JsfTestConfiguration(CoreJsfTestConfiguration.class)
class SwitchRendererTest extends AbstractComponentRendererTest<SwitchRenderer> implements ComponentConfigurator {

    @Override
    public void configureComponents(final ComponentConfigDecorator decorator) {
        decorator.registerUIComponent(ColumnComponent.class).
        registerRenderer(LayoutComponentRenderer.class);
   }

    @Override
    protected UIComponent getComponent() {
        final SwitchComponent component = new SwitchComponent();
        component.setId(testComponent);
        component.setTitleValue(titleValue);
        component.setTitleKey(titleKey);
        component.setOnTextValue(onText);
        component.setOffTextValue(offText);
        component.setOnTextKey(onTextKey);
        component.setOffTextKey(offTextKey);
        component.setStyle(style);
        component.setSize(3);
        component.setStyleClass(styleClass);
        return component;
    }

   @Test
   void shouldRenderMinimal() {
       final SwitchComponent component = (SwitchComponent) getComponent();
       component.processEvent(new PostAddToViewEvent(component));
       component.processEvent(new PreRenderComponentEvent(component));

       final HtmlTreeBuilder expected = buildHtmlTree(false, false);
       assertRenderResult(component, expected.getDocument());
   }

   @Test
   void shouldRenderDisabled() {
       final SwitchComponent component = (SwitchComponent) getComponent();
       component.setDisabled(true);

       component.processEvent(new PostAddToViewEvent(component));
       component.processEvent(new PreRenderComponentEvent(component));

       final HtmlTreeBuilder expected = buildHtmlTree(false, true);
       assertRenderResult(component, expected.getDocument());
   }
   /**
    * <div id="testComponent_container"
    * name="testComponent_container"
    * data-switch-disabled="true|false">
    * <div class="col-sm-6 switch-placing">
    * <label class="switch">
    * <input id="testComponent" name="testComponent"/>
    * <span class="slider round"/>
    * </label>
    * <span class="switch-text" data-item-active="true">onText</span>
    * <span class="switch-text" data-item-active="false">offText</span>
    * </div>
    * </div>
    */
   private HtmlTreeBuilder buildHtmlTree(final boolean isActive, final boolean isDisabled) {
     final HtmlTreeBuilder expected = new HtmlTreeBuilder()
     // container
     .withNode(Node.DIV)
     .withAttributeNameAndId("testComponent_container")
     .withAttribute("data-switch-disabled", String.valueOf(isDisabled))
     .withAttribute(AttributeName.CLASS, styleClass)
     .withAttribute(AttributeName.STYLE, style)

     // column
     .withNode(Node.DIV)
     .withAttribute(AttributeName.CLASS, default_column_size + " switch-placing")

     // label
     .withNode(Node.LABEL)
     .withAttribute(AttributeName.CLASS, "switch")
     .withAttribute(AttributeName.TITLE, titleValue)

     // checkbox
     .withNode(Node.INPUT)
     .withAttributeNameAndId("testComponent")
     .currentHierarchyUp()

     // slider
     .withNode(Node.SPAN)
     .withAttribute(AttributeName.CLASS, "slider round")
     .currentHierarchyUp()

     // leaving label
     .currentHierarchyUp()

     // on text
     .withNode(Node.SPAN)
     .withAttribute(AttributeName.CLASS, "switch-text" + (!isActive ? " hidden" : ""))
     .withAttribute(AttributeName.DATA_ITEM_ACTIVE, "true")
     .withTextContent(onText)
     .currentHierarchyUp()

     // off text
     .withNode(Node.SPAN)
     .withAttribute(AttributeName.CLASS, "switch-text" + (isActive ? " hidden" : ""))
     .withAttribute(AttributeName.DATA_ITEM_ACTIVE, "false")
     .withTextContent(offText)
     .currentHierarchyUp()

     // leaving column
     .currentHierarchyUp();

      return expected;
    }
}
----